exercise/base/urls.py
from django.urls import path
from django.contrib import admin
from . import views
app_name = 'basic_app'

urlpatterns= [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout_tag'),
    path('special/', views.special, name='special')
]

exercise/exercise/urls.py
from django.contrib import admin
from django.urls import path, include
from base import views
app_name = 'basic_app'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

exercise/base/models.py
from django.db import models
from django.contrib.auth.models import User
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete= models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(blank=True, upload_to='profile_pics')
    def __str__(self):
        return self.user.username

exercise/base/forms.py
from . models import UserProfile
from django import forms
from django.contrib.auth.models import User
from django.core import validators
class UserProfileForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    rep_password = forms.CharField(widget=forms.PasswordInput, label = 'Confirm your password')
    botcatcher = forms.CharField(widget=forms.HiddenInput, required=False)
    def catch_bot(self):
        botcatcher = self.cleaned_data['botcatcher']
        if len(botcatcher) > 0:
            raise forms.ValidationError('Bot error!!!')
        return botcatcher
    def clean(self):
        all_clean = super().clean()
        password = all_clean['password']
        email = all_clean['email']
        rep_password = all_clean['rep_password']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Email already exists')
        if password != rep_password:
            raise forms.ValidationError('Please ensure that your password are same')  

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfile(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('portfolio_site', 'profile_pic')
        
        

exercise/base/views.py
from django.shortcuts import render
from .forms import UserProfile, UserProfileForm

from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import resolve
from django.contrib.auth.decorators import login_required
from django.urls import reverse



def home(request):
    return render(request, 'base/index.html')

def register(request):
    user_form = UserProfileForm
    profile_form = UserProfile
    registered = False
    if request.method == 'POST':
        user_form = user_form(request.POST)
        profile_form = profile_form(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
    return render(request, 'base/register.html', {'form': user_form, 'port': profile_form, 'registered': registered})

@login_required
def special(request):
    return HttpResponse('You are logged in')

@login_required
def user_logout(request):
    logout(request)
    return render(request, 'base/index.html')

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                print('active')
                return render(request, 'base/index.html')
            else:
                print('Invalid login details')
        else:
            print('User is not logged in')
            return HttpResponse('Login was not succesfull, make sure you are logged in')
    return render(request, 'base/login.html')

exercise/base/templates/base/index.html
{% include 'base/temp.html' %}
<div class="wrapp-items">
    <div class="text-content">
        {% if user.is_authenticated %}
        <h1 style="text-align: center;">Welcome to home page {{user.username}}</h1>
        {% else %}
        <h1 style="text-align: center;">Welcome to home page</h1>
        {% endif %}
    </div>
</div>

exercise/base/templates/base/login.html
{% include 'base/nav.html' %}
<div class="wrapper">
    <div class="header" style="margin-bottom: 30px;">
        <h3>Login page</h3>
    </div>
    <form method="post">
        <label for="username">Username</label>
        <input type="text" name="username" id="">

        <label for="password">Password</label>
        <input type="password" name="password" id="">
        {% csrf_token %}
        <input class="submit-content" type="submit" value="Login">
    </form>
</div>

exercise/base/templates/base/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;1,100;1,200;1,300;1,400&display=swap" rel="stylesheet">

<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;1,100;1,200;1,300;1,400&display=swap');
    </style>
    {% load static %}
    <link rel="stylesheet" href="{% static 'stat.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <h1><a style="color: black; text-decoration: none;" href="{% url 'basic_app:home' %}">My simple nav</a></h1>
        <ul>
            {% if user.is_authenticated %}
            <li><a href="{% url 'admin:index' %}">Django</a></li>
            <li><a class="{% if page == 'page1' %} active {% endif %}" href="{% url 'basic_app:home' %}">Home</a></li>
            <li><a class="{% if page == 'page2' %} active {% endif %}"  href="{% url 'basic_app:logout_tag' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'admin:index' %}">Django</a></li>
            <li><a class="{% if page == 'page1' %} active {% endif %}" href="{% url 'basic_app:home' %}">Home</a></li>
            <li><a class="{% if page == 'page2' %} active {% endif %}"  href="{% url 'basic_app:login' %}">Login</a></li>
            <li><a class="{% if page == 'page3' %} active {% endif %}" href="{% url 'basic_app:register' %}" %}">Register</a></li>
            {% endif %}
        </ul>
    </div>
</body>
</html>

exercise/base/templates/base/register.html
{% include 'base/temp.html' %}

{% if registered %}
<body>
    Welcome, you have been registered 
</body>
{% else %}
<body>
    <div class="wrapper">
        <div class="header" style="margin-bottom: 30px;">
            <h3>Register page</h3>
        </div>
        <form enctype="multipart/form-data" method="post">
            {{form}}
            {{port}}
            {% csrf_token %}
            <input class="submit-content" type="submit" value="Register">
        </form>
    </div>
</body>
{% endif %}

exercise/base/templates/base/temp.html
{% extends 'base/nav.html' %}
{% block content %}

{% endblock %}